import { collectionRef } from "./index.js";
import { getDocs, addDoc } from "firebase/firestore/lite";

// Get a list of the documents in the collection
export async function getDocuments() {
  try {
    const querySnapshot = await getDocs(collectionRef);
    const documents = [];
    querySnapshot.forEach((doc) => {
      documents.push({ id: doc.id, ...doc.data() });
    });
    return documents;
  } catch (error) {
    console.error("Error fetching documents:", error);
    throw error;
  }
}

// Add a new document, id is autogenerated.
export async function addDocument(data) {
  return addDoc(collectionRef, data)
    .then((docRef) => {
      return docRef.id; // ID of the added document
    })
    .catch((error) => {
      console.error("Error adding document:", error);
      throw error;
    });
}
